version: '3.8'
services:
  mysql:
    build: ./mysql
    image: "mysql:2021.11"
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-${COMPOSE_PROJECTNAME}
    ports: 
      - "3306:3306"
    volumes:
      # volumen para cambios realizados en bd
      - "./volmysql:/var/lib/mysql"
      # volumen para primer build crear bd-boards-inserts
      # - "./mysql/00-bd:/docker-entrypoint-initdb.d"
    networks:
      red-pr200:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
  # adminer:
  #   image: adminer
  #   container_name: adminer-pr200
  #   restart: always
  #   networks:
  #     red-pr200:
  #   ports:
  #     - 8082:8080

  php:
    build: ./php
    image: "php:2021.11"
    container_name: php-${COMPOSE_PROJECTNAME}
    volumes:
      - "${DIR_PROYECTO}:/var/www/html"
    networks:
      red-pr200:
    links:
      - mysql

  apache:
    build: ./apache
    image: "apache:2021.11"
    container_name: apache-${COMPOSE_PROJECTNAME}
    ports:
      - "80:80"
      # puerto por defecto para emitir con SSL
      # - "443:443"
    volumes:
      # vol para operar en la aplicación 
      - "${DIR_PROYECTO}:/var/www/html"
      # vols almacenaje certificados
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
    networks:
      red-pr200:
    environment:
      LETS_ENCRYPT_EMAIL: ${LETS_ENCRYPT_EMAIL} 
      LETS_ENCRYPT_DOMINIOS: ${LETS_ENCRYPT_DOMINIOS}
      LETS_ENCRYPT_DIRECTORIO: ${LETS_ENCRYPT_DIRECTORIO}
    links:
      - php

networks:
  red-pr200:
    name: red-pr200

volumes:
  varletsencrypt:
    name: pr200-varletsencrypt
  etcletsencrypt:
    name: pr200-etcletsencrypt