DROP DATABASE IF EXISTS  `zonas`;
CREATE DATABASE `zonas`;
USE  `zonas`;

CREATE TABLE `Z400`(
    `idregistro` BIGINT UNSIGNED AUTO_INCREMENT,
    `fh` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `cantluz` INT,
    PRIMARY KEY (idregistro)
);

CREATE TABLE `B401`(
    `idregistro`BIGINT UNSIGNED AUTO_INCREMENT,
    `fh` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `entrada` BIT DEFAULT 1,
    PRIMARY KEY (idregistro)
);

CREATE TABLE `B402`(
    `idregistro`BIGINT UNSIGNED AUTO_INCREMENT,
    `fh` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `entrada` BIT DEFAULT 1,
    PRIMARY KEY (idregistro)
);
